baseurl = "https://djbelyak.github.io/"
languageCode = "ru-ru"
title = "Радио-Т Подкаст"
description = """
Еженедельные разговоры на темы хайтек, высоких компьютерных технологий, гаджетов, облаков, программирования и прочего интересного из мира ИТ.
"""

[[menu.main]]
	name = "Подкасты"
    url = "/"
    weight = -110
[[menu.main]]
	name = "Архивы"
	url = "/archives"
	weight = -100
[[menu.main]]
	name = "Вещание"
	url = "/online"
	weight = -90
[[menu.main]]
	name = "Подписка"
	url = "/feeds"
	weight = -80
[[menu.main]]
	name = "FAQ"
	url = "/faq"
	weight = -70
[[menu.main]]
	name = "Реклама"
	url = "/advertising"
	weight = -60

